server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: product-server
        uri: lb://productserver
        predicates:
        - Path=/products/**
        filters:
        - RewritePath=/products/(?<path>.*), /$\{path}
      - id: review-server
        uri: lb://reviewserver
        predicates:
        - Path=/reviews/**
        filters:
        - RewritePath=/reviews/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway
