server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: review-service
        uri: lb://reviewservice
        order: 0
        predicates:
        - Path=products/{product-id}/reviews/**
        filters:
        - RewritePath=products/(?<product-id>.*)/reviews/(?<review_id>.*), /reviews/hello
      - id: product-service
        uri: lb://productservice
        order: 1
        predicates:
        - Path=/products/**
        filters:
        - RewritePath=/products/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway
