server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost:8761}/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://productservice
        predicates:
        - Path=/products/**
        filters:
        - RewritePath=/products/(?<path>.*), /$\{path}
      - id: review-service
        uri: lb://reviewservice
        predicates:
        - Path=/reviews/**

management:
  endpoints:
    web:
      exposure:
        include: gateway
